export type AssetType = "dataset" | "dashboard" | "mlModel" | "activation";

export type Asset = {
  urn: string;
  name: string;
  subtitle: string;
  type: AssetType;
  platform: string;
  owner: string;
  tier: 1 | 2 | 3;
  tags: string[];
  fields: string[];
  upstreamUrns: string[];
};

export type ChangeKind = "privacy" | "type" | "rename";

export type Scenario = {
  id: string;
  eyebrow: string;
  title: string;
  summary: string;
  targetUrn: string;
  targetField: string;
  before: string;
  after: string;
  kind: ChangeKind;
  pullRequest: string;
};

export type AssetImpact = Asset & {
  depth: number;
  severity: "critical" | "high" | "medium" | "low";
  reason: string;
};

export type RolloutPhase = {
  label: string;
  title: string;
  owner: string;
  checks: string[];
};

export type Analysis = {
  scenario: Scenario;
  impacted: AssetImpact[];
  riskScore: number;
  riskLabel: "Critical" | "High" | "Moderate";
  confidence: number;
  owners: string[];
  criticalCount: number;
  maxDepth: number;
  findings: string[];
  phases: RolloutPhase[];
  generatedSql: string;
  markdown: string;
};

const kindBaseRisk: Record<ChangeKind, number> = {
  privacy: 44,
  type: 37,
  rename: 31,
};

function severityFor(asset: Asset, depth: number, scenario: Scenario): AssetImpact["severity"] {
  if (
    asset.tier === 1 ||
    asset.tags.includes("PII") ||
    (scenario.kind === "type" && asset.type === "dashboard")
  ) {
    return "critical";
  }
  if (asset.tier === 2 || depth <= 1) return "high";
  if (depth === 2) return "medium";
  return "low";
}

function reasonFor(asset: Asset, depth: number, scenario: Scenario) {
  if (asset.urn === scenario.targetUrn) {
    return `${scenario.targetField} is modified at the source contract`;
  }
  if (asset.type === "dashboard") {
    return `Executive metric consumes the changed field ${depth} hop${depth === 1 ? "" : "s"} downstream`;
  }
  if (asset.type === "mlModel") {
    return "Feature contract and historical training parity can diverge";
  }
  if (asset.type === "activation") {
    return "Customer audience sync can change silently without a schema error";
  }
  if (asset.tags.includes("PII")) {
    return "PII propagation requires policy and masking verification";
  }
  return `Transitive lineage dependency at depth ${depth}`;
}

function makePlan(scenario: Scenario, impacted: AssetImpact[], owners: string[]): RolloutPhase[] {
  const criticalNames = impacted
    .filter((asset) => asset.severity === "critical")
    .slice(0, 3)
    .map((asset) => asset.name);

  return [
    {
      label: "01",
      title: "Contract first",
      owner: owners[0] ?? "Data Platform",
      checks: [
        `Add ${scenario.targetField} compatibility assertion`,
        `Pin current contract as ${scenario.before}`,
        "Block merge on downstream contract failures",
      ],
    },
    {
      label: "02",
      title: "Dual-run the change",
      owner: owners[1] ?? owners[0] ?? "Analytics",
      checks: [
        `Materialize old and new values for ${scenario.targetField}`,
        `Compare row counts and null rates across ${Math.max(1, impacted.length)} assets`,
        `Require sign-off from ${criticalNames.join(", ") || "critical consumers"}`,
      ],
    },
    {
      label: "03",
      title: "Progressive rollout",
      owner: owners[2] ?? owners[0] ?? "Data Platform",
      checks: [
        "Deploy to 10%, 50%, then 100% of scheduled runs",
        "Watch freshness, volume, and semantic assertions",
        "Keep the compatibility view for one release window",
      ],
    },
  ];
}

function makeSql(scenario: Scenario) {
  const safeField = scenario.targetField.replace(/[^a-zA-Z0-9_]/g, "_");
  if (scenario.kind === "privacy") {
    return `-- Compatibility view generated by LineageShield
create or replace view analytics.customer_contact_safe as
select
  * exclude (${safeField}),
  sha2(lower(trim(${safeField})), 256) as ${safeField}_hash,
  ${safeField} as ${safeField}_legacy
from staging.customer_contact;

-- Remove ${safeField}_legacy after downstream sign-off.`;
  }
  if (scenario.kind === "type") {
    return `-- Guard the narrowing cast before changing the contract
select
  count_if(try_cast(${safeField} as number(18,2)) is null) as invalid_rows,
  max(abs(${safeField})) as observed_max
from analytics.orders
having invalid_rows > 0 or observed_max > 9999999999999999.99;`;
  }
  return `-- Non-breaking rename window
select
  * exclude (${safeField}),
  ${safeField} as customer_lifetime_value,
  ${safeField} as ${safeField}_deprecated
from features.customer_value;

-- Alert on reads of ${safeField}_deprecated before removal.`;
}

export function analyzeLineage(
  assets: Asset[],
  scenario: Scenario,
): Analysis {
  const downstream = new Map<string, Asset[]>();
  for (const asset of assets) {
    for (const upstreamUrn of asset.upstreamUrns) {
      const children = downstream.get(upstreamUrn) ?? [];
      children.push(asset);
      downstream.set(upstreamUrn, children);
    }
  }

  const assetByUrn = new Map(assets.map((asset) => [asset.urn, asset]));
  const queue: Array<{ urn: string; depth: number }> = [
    { urn: scenario.targetUrn, depth: 0 },
  ];
  const visited = new Set<string>();
  const impacted: AssetImpact[] = [];

  while (queue.length) {
    const current = queue.shift();
    if (!current || visited.has(current.urn)) continue;
    visited.add(current.urn);

    const asset = assetByUrn.get(current.urn);
    if (asset) {
      impacted.push({
        ...asset,
        depth: current.depth,
        severity: severityFor(asset, current.depth, scenario),
        reason: reasonFor(asset, current.depth, scenario),
      });
    }

    for (const child of downstream.get(current.urn) ?? []) {
      queue.push({ urn: child.urn, depth: current.depth + 1 });
    }
  }

  impacted.sort((a, b) => a.depth - b.depth || a.name.localeCompare(b.name));
  const owners = [...new Set(impacted.map((asset) => asset.owner))];
  const criticalCount = impacted.filter((asset) => asset.severity === "critical").length;
  const highCount = impacted.filter((asset) => asset.severity === "high").length;
  const piiCount = impacted.filter((asset) => asset.tags.includes("PII")).length;
  const maxDepth = Math.max(...impacted.map((asset) => asset.depth), 0);
  const riskScore = Math.min(
    99,
    kindBaseRisk[scenario.kind] +
      criticalCount * 9 +
      highCount * 4 +
      Math.min(15, impacted.length * 2) +
      Math.min(8, piiCount * 3),
  );
  const riskLabel: Analysis["riskLabel"] =
    riskScore >= 85 ? "Critical" : riskScore >= 68 ? "High" : "Moderate";
  const confidence = Math.min(99, 80 + Math.min(12, impacted.length * 2) + owners.length);
  const findings = [
    `${impacted.length} assets are reachable across ${maxDepth} lineage hops.`,
    `${criticalCount} Tier 1 or policy-sensitive consumers need explicit approval.`,
    `${owners.length} ownership groups must coordinate the rollout.`,
    scenario.kind === "privacy"
      ? `${piiCount} assets retain PII semantics after the proposed transformation.`
      : "A compatibility window prevents silent consumer drift.",
  ];
  const phases = makePlan(scenario, impacted, owners);
  const generatedSql = makeSql(scenario);

  const markdown = [
    `# LineageShield rollout — ${scenario.title}`,
    "",
    `**Risk:** ${riskLabel} (${riskScore}/100) · **Confidence:** ${confidence}%`,
    `**Source:** ${scenario.pullRequest}`,
    "",
    "## Blast radius",
    ...impacted.map(
      (asset) =>
        `- [${asset.severity.toUpperCase()}] ${asset.name} — ${asset.reason} (${asset.owner})`,
    ),
    "",
    "## Rollout",
    ...phases.flatMap((phase) => [
      `### ${phase.label}. ${phase.title} — ${phase.owner}`,
      ...phase.checks.map((check) => `- [ ] ${check}`),
      "",
    ]),
    "## Generated guardrail",
    "```sql",
    generatedSql,
    "```",
    "",
    "_Generated from DataHub lineage, ownership, tags, tiers, and schema context._",
  ].join("\n");

  return {
    scenario,
    impacted,
    riskScore,
    riskLabel,
    confidence,
    owners,
    criticalCount,
    maxDepth,
    findings,
    phases,
    generatedSql,
    markdown,
  };
}
